/** Seed catalog. Do not add blocked apps. LightStudio/getlcai are not attributed to keikodev. */

const CHAIN = {
  chainId: 9200,
  rpcUrl: "https://rpc.mainnet.lightchain.ai",
  nativeCurrency: { symbol: "LCAI", decimals: 18 },
  onramp: "https://bridge.lightchain.ai/",
};

const JOB_REGISTRY = "0xfB15F90298e4CcD7106E76fFB5e520315cC42B0b";
const DELEGATE = "0x1250Fc88c86469DFa4bcd429c0A20d49f884dF45";
const ORCAVAULT_PAY = "0xbb0ab4c9E15a20661CA0C4d2b6f5D32A7EdF7646";

const SET_DELEGATE_ALLOWANCE_ABI = [
  {
    name: "setDelegateAllowance",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "delegate", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
];

function base(extra) {
  return {
    version: "1",
    ...CHAIN,
    endpoint: null,
    auth: "none",
    tools: [],
    payment: { kind: "human_only" },
    verified: true,
    status: "directory-only",
    ...extra,
  };
}

/** Tier A: OrcaPod ∩ App Manager ACTIVE (16). Only OrcaVault is transactable. */
export const TIER_A = [
  base({
    id: "orcavault",
    name: "OrcaVault",
    description: "Permanent on-chain memory and file storage for agents on Lightchain.",
    category: "storage",
    owner: "keikodev",
    url: "https://orcavault.win",
    endpoint: "https://orcavault-production.up.railway.app",
    healthUrl: "https://orcavault-production.up.railway.app/api/relay-status",
    auth: "wallet",
    tools: ["check_access", "relay_status", "store_memory"],
    payment: {
      kind: "native_transfer",
      kinds: ["native_transfer", "aivm_allowance"],
      spender: DELEGATE,
      jobRegistry: JOB_REGISTRY,
      call: {
        native_transfer: {
          to: ORCAVAULT_PAY,
          token: "native",
          note: "One-time native LCAI transfer to unlock agent uploads; app quotes the live fee.",
        },
        aivm_allowance: {
          to: JOB_REGISTRY,
          method: "setDelegateAllowance",
          abi: SET_DELEGATE_ALLOWANCE_ABI,
          delegate: DELEGATE,
        },
      },
    },
    status: "transactable",
    tier: "A",
  }),
  base({
    id: "binai",
    name: "Binai",
    description: "Personal AI assistant with memory, chat, notes and reminders.",
    category: "ai",
    owner: "keikodev",
    url: "https://binai.win",
    healthUrl: "https://binai.win",
    tier: "A",
  }),
  base({
    id: "lightjury",
    name: "LightJury",
    description: "A jury of independent AIs renders an advisory verdict on a dispute.",
    category: "ai",
    owner: "keikodev",
    url: "https://lightjury.win",
    healthUrl: "https://lightjury.win",
    tier: "A",
  }),
  base({
    id: "lightstudio",
    name: "LightStudio",
    description: "Create AI images, video, voice, and songs.",
    category: "media",
    owner: "community",
    url: "https://lightstudio.fun",
    healthUrl: "https://lightstudio.fun",
    tier: "A",
  }),
  base({
    id: "orcalearn",
    name: "OrcaLearn",
    description: "AI-assisted learning and lesson tools on Lightchain.",
    category: "tools",
    owner: "keikodev",
    url: "https://orcalearn.ai",
    healthUrl: "https://orcalearn.ai",
    tier: "A",
  }),
  base({
    id: "lightweather",
    name: "LightWeather",
    description: "Weather with Lightchain AIVM-powered explanations.",
    category: "tools",
    owner: "keikodev",
    url: "https://lightweather.win",
    healthUrl: "https://lightweather.win",
    tier: "A",
  }),
  base({
    id: "sc-explainer",
    name: "SC Explainer",
    description: "Paste a contract address and get a plain-English explanation.",
    category: "security",
    owner: "keikodev",
    url: "https://smartcontractexplainer.xyz",
    healthUrl: "https://smartcontractexplainer.xyz",
    tier: "A",
  }),
  base({
    id: "orcaappbuilder",
    name: "OrcaAppBuilder",
    description: "Plan, build, and troubleshoot Lightchain applications.",
    category: "tools",
    owner: "keikodev",
    url: "https://orcaappbuilder.win",
    healthUrl: "https://orcaappbuilder.win",
    tier: "A",
  }),
  base({
    id: "orcamail",
    name: "OrcaMail",
    description: "Wallet-to-wallet encrypted messaging on Lightchain.",
    category: "social",
    owner: "keikodev",
    url: "https://orcamail.ai",
    healthUrl: "https://orcamail.ai",
    tier: "A",
  }),
  base({
    id: "orcamint",
    name: "OrcaMint",
    description: "Mint, buy, and sell NFTs on Lightchain.",
    category: "nft",
    owner: "keikodev",
    url: "https://orcamint.xyz",
    healthUrl: "https://orcamint.xyz",
    tier: "A",
  }),
  base({
    id: "lighttube",
    name: "LightTube",
    description: "Community video stored through Lightchain.",
    category: "media",
    owner: "keikodev",
    url: "https://lighttube.win",
    healthUrl: "https://lighttube.win",
    tier: "A",
  }),
  base({
    id: "lighttunes",
    name: "LightTunes",
    description: "Music on Lightchain — upload, stream, and tip in LCAI.",
    category: "media",
    owner: "keikodev",
    url: "https://lighttunes.win",
    healthUrl: "https://lighttunes.win",
    tier: "A",
  }),
  base({
    id: "myice",
    name: "MyICE",
    description: "Emergency health ID vault with optional chain backup.",
    category: "health",
    owner: "keikodev",
    url: "https://myice.win",
    healthUrl: "https://myice.win",
    tier: "A",
  }),
  base({
    id: "orcaguard",
    name: "OrcaGuard",
    description: "Crypto safety: contracts, URLs, and wallet checks.",
    category: "security",
    owner: "keikodev",
    url: "https://orcaguard.win",
    healthUrl: "https://orcaguard.win",
    tier: "A",
  }),
  base({
    id: "emojis-stickers",
    name: "Emojis & Stickers",
    description: "AI emoji generator and Discord bot.",
    category: "media",
    owner: "keikodev",
    url: "https://emojisandstickers.xyz",
    healthUrl: "https://emojisandstickers.xyz",
    tier: "A",
  }),
  base({
    id: "topten",
    name: "Top Ten Presales",
    description: "AI-analyzed crypto presale rankings.",
    category: "finance",
    owner: "keikodev",
    url: "https://keiko-dev-lcai.github.io/topten/",
    healthUrl: "https://keiko-dev-lcai.github.io/topten/",
    tier: "A",
  }),
];

/** Tier B from lightapps.ai (2026-10-09). Skip junk and retired node builder. */
export const TIER_B = [
  base({
    id: "filament",
    name: "Filament",
    description: "Non-custodial DEX and memecoin launchpad on Lightchain.",
    category: "defi",
    owner: "community",
    url: "https://filament.exchange",
    healthUrl: "https://filament.exchange",
    tier: "B",
  }),
  base({
    id: "lightnode",
    name: "LightNode",
    description: "Community toolkit for Lightchain workers, wallet, and SDK.",
    category: "ai",
    owner: "community",
    url: "https://lightnode.app/",
    healthUrl: "https://lightnode.app/",
    tier: "B",
  }),
  base({
    id: "gaim-arcade",
    name: "GAIM Arcade",
    description: "AI-powered game creation with a Lightchain-ready registry preview.",
    category: "gaming",
    owner: "community",
    url: "https://www.gaimarcade.com/lcai",
    healthUrl: "https://www.gaimarcade.com/lcai",
    tier: "B",
  }),
  base({
    id: "lightchain-bridge",
    name: "Lightchain Bridge",
    description: "Move assets between Ethereum and Lightchain. Buy & Bridge for ETH → native LCAI.",
    category: "infrastructure",
    owner: "protocol",
    url: "https://bridge.lightchain.ai/",
    healthUrl: "https://bridge.lightchain.ai/",
    tier: "B",
  }),
  base({
    id: "lightchain-explorer",
    name: "Lightchain Explorer",
    description: "Inspect Lightchain blocks, transactions, contracts, and wallets.",
    category: "infrastructure",
    owner: "protocol",
    url: "https://mainnet.lightscan.app/",
    healthUrl: "https://mainnet.lightscan.app/",
    tier: "B",
  }),
  base({
    id: "worker-explorer",
    name: "Worker Explorer",
    description: "Browse Lightchain workers, stakes, and supported models.",
    category: "ai",
    owner: "protocol",
    url: "https://workers.lightchain.ai/",
    healthUrl: "https://workers.lightchain.ai/",
    tier: "B",
  }),
  base({
    id: "lighttable",
    name: "LightTable",
    description: "Community cookbook where recipes earn their keep.",
    category: "ai",
    owner: "community",
    url: "https://lighttable.fyi/",
    healthUrl: "https://lighttable.fyi/",
    tier: "B",
  }),
  base({
    id: "lcai-faucet",
    name: "LCAI Faucet",
    description: "Testnet LCAI in a few clicks.",
    category: "tools",
    owner: "protocol",
    url: "https://lightfaucet.ai/",
    healthUrl: "https://lightfaucet.ai/",
    tier: "B",
  }),
  base({
    id: "lightchain-ide",
    name: "Lightchain IDE",
    description: "Write, compile, and deploy contracts in the browser.",
    category: "tools",
    owner: "protocol",
    url: "https://deploy.lightchain.ai/",
    healthUrl: "https://deploy.lightchain.ai/",
    tier: "B",
  }),
  base({
    id: "lightchallenge",
    name: "LightChallenge",
    description: "Stake on fitness and gaming challenges, verified by AI.",
    category: "fitness",
    owner: "community",
    url: "https://lightchallenge.app/",
    healthUrl: "https://lightchallenge.app/",
    tier: "B",
  }),
  base({
    id: "lightchain-ai-chat",
    name: "Lightchain AI Chat",
    description: "Official wallet-connected AI chat for the Lightchain ecosystem.",
    category: "ai",
    owner: "protocol",
    url: "https://chat.lightchain.ai/",
    healthUrl: "https://chat.lightchain.ai/",
    tier: "B",
  }),
  base({
    id: "getlcai",
    name: "GetLcai",
    description: "Turn ETH into native LCAI on Lightchain.",
    category: "infrastructure",
    owner: "community",
    url: "https://getlcai.win",
    healthUrl: "https://getlcai.win",
    tier: "B",
  }),
];

export const SEED = [...TIER_A, ...TIER_B];

export const BLOCKED_IDS = new Set([
  "lightchat",
  "orcafiles",
  "lightmall",
  "lightview",
  "node-builder",
  "orcanode",
  "lightapps-media-test",
]);
